### ISSUE TITLE
No xcworkspace file in the repo?

### ISSUE THREAD

**Issue by mkostersitz** [mihahribar/dilbert-ios#1]
Hi,

great app thanks for posting it. Sorry for the Newbie question, 
I wanted to play around with the code and cloned it down. Installed cocoapods, and ran pod install which produces an error: 
Analyzing dependencies
[!] The dependency `Kanna` is not used in any concrete target.
And there is no workspace file I could open.
Do you have any pointers on how to get this fixed?

thanks

mike

**Comment by mihahribar** [comment]
Hey mike, haven't updated this repo in a while so it did not build anymore. The `Podfile` was very of out date so I updated it. Converted to latest Swift 3 syntax while I was at it. Hope it works now. 

FYI this is not the best code, was used just to test-drive swift. Perhaps someday I'll complete the project :)

**Comment by mkostersitz** [comment]
I am learning too :) and thought a Dilbert App would be a fun way to start. Your code gave me a bunch of great ideas. Thanks for making it build again.
